### ISSUE TITLE
Standalone Puple Chest Mod

### ISSUE THREAD

**Issue by InitialDet** [JeffreyTangMain/Octopath-Traveler-Mods#1]
Hello, do you think you could share a standalone version of the "Purple chests are now all red chests" mod?

**Comment by JeffreyTangMain** [comment]
Sorry, I don't have the tools to create another pak, but I can tell you the file I changed if you want to create your own.

If you unpack my mod, you'd look for the "ObjectData" files in Content\Object\Database.

Just take those out, create your own mod with only those files, and then you've isolated those changes.

What I specifically did to those files was change the "ObjectType" parameter from 3 (purple chest) to 2 (red chest).

If you need help, Octopath Traveller has a Discord with a modding section here: https://discord.gg/t43Kbrp.

**Comment by InitialDet** [comment]
Thanks for the quick answer!

Btw, is there any other change in the Database file other then the chests parameters?

**Comment by JeffreyTangMain** [comment]
I do not believe there are any further changes, but you could always check against the decompiled original Octopath file if you want to be 100% sure.
